# Generated by Django 6.0.4 on 2026-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/'),
        ),
        migrations.AddField(
            model_name='step',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
