# Generated by Django 6.0.4 on 2026-04-21 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_step_image_step_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
