# Generated by Django 6.0.4 on 2026-04-25 22:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_step_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
