# Generated by Django 6.0.4 on 2026-05-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_step_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='role',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
