# Generated by Django 6.0.4 on 2026-05-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_protocol_role_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
    ]
