# Generated by Django 6.0.4 on 2026-05-19 00:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_protocol_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('university_logo', models.ImageField(upload_to='about/logos/')),
                ('college_logo', models.ImageField(upload_to='about/logos/')),
                ('group_image', models.ImageField(upload_to='about/group/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('group_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
