# Generated by Django 6.0.4 on 2026-05-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='college_logo',
        ),
        migrations.RemoveField(
            model_name='about',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='group_image',
            field=models.ImageField(upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='goal_icons/')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.about')),
            ],
        ),
    ]
