# Generated by Django 6.0.4 on 2026-05-19 18:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_about_college_logo_alter_about_group_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='projectgoal',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
