# Generated by Django 6.0.4 on 2026-05-21 02:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_about_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
